name: CreateAcumulateDataCSV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  get_brasil_io_data_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Retrieve Brasil.IO data
        run: python ./new_scripts/get_acumulate_data.py ${{ secrets.BRASIL_IO_API_KEY }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --allow-empty -m ":robot: Updated CSV"
          git push
