name: CreateCSV

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0 * * *'

jobs:
  get_brasil_io_data_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: installing dependencies
        run: |
          pip install plotly==4.14.3
          pip install pandas
          pip install dominate
                
      - name: gerating html file
        run: python ./scripts/html.py >> ./index.html

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --allow-empty -m ":robot: Updated CSV"
          git push